# E2E Test Host Configurations
# Host connection info (api_endpoint, node_name) is read from tfvars files

defaults:
  ssh_user: root
  inner_vm_id: 99913
  test_vm_id: 99901
  packer_release_repo: homestak-dev/packer
  packer_release_tag: v0.1.0-rc1
  packer_image: debian-12-custom.qcow2

hosts:
  pve:
    tfvars_file: secrets/pve.tfvars

  father:
    tfvars_file: secrets/father.tfvars
